### PR TITLE
Fix cli.py file permissions (+x)

### PR DESCRIPTION
**Pull request by Fale**
[Review on Reviewable](https://reviewable.io/reviews/coagulant/coveralls-python/105)

### CODE REVIEW

**Comment by coagulant** [comment]
Can you elaborate, what is the purpose of permission change?

**Comment by Fale** [comment]
This file has the shabang to be executed, so it has to be executable in order to do so

**Comment by coagulant** [comment]
You propose to run cli.py manually? I suppose having entry point in setup.py is enough?

**Comment by Fale** [comment]
If cli.py should NOT be executed, it should not contain a main method and a shabang. Why should a file that is not an entry point contains a shabang and a main method?

**Comment by TheKevJames** [comment]
@Fale `cli.py` is indeed an entrypoint, but it's not meant to be executed manually (ie. by running `./cli.py`). Instead, we define it as a [distutils entrypoint](http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) in the coveralls [setup.py](https://github.com/coagulant/coveralls-python/blob/master/setup.py#L30).

Running this script manually may cause unforeseen issues, since it is not how this project is meant to be used. Rather than making `cli.py` executable, we can just remove the shebang to make it more clear that this script should not be run as-is.

**Comment by TheKevJames** [comment]
Test failures look unrelated to this PR; PyPy3 tests are failing since the version of PyPy3 being installed uses Python 3.2.x which pip no longer supports. This should be fixed in a different PR by [updating our PyPy3 target](https://morepypy.blogspot.com/2016/10/pypy3-550-released.html).

Otherwise, this PR looks good -- thanks for the contribution, but won't be merged until the [feature freeze while we look for a new maintainer](https://github.com/coagulant/coveralls-python/issues/122) is over.

**Comment by TheKevJames** [comment]
Thanks for the contribution!

**Pull request merged**
